version: "3.9"
services:
  sample:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
